vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: /uploads/picture
            upload_destination: '%kernel.project_dir%/public/uploads/picture'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
