version: "2"
services:
    database:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: video
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - persistent:/var/lib/mysql
        networks:
            - default

    phpmyadmin:
        image: phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: database
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
            - "8080:80"
        depends_on:
            - database
volumes:
    persistent:
